from dataclasses import dataclass
from enum import StrEnum


class CodigoBloqueo(StrEnum):
    SIN_COSTOS_INDIRECTOS_REGISTRADOS = "SIN_COSTOS_INDIRECTOS_REGISTRADOS"
    SIN_PERFIL_CAPACIDAD = "SIN_PERFIL_CAPACIDAD"
    SIN_TIEMPO_ATENCION = "SIN_TIEMPO_ATENCION"
    DURACION_INVALIDA = "DURACION_INVALIDA"
    ESPACIADO_FUERA_RANGO = "ESPACIADO_FUERA_RANGO"
    SIN_ESPACIADO_PREDETERMINADO = "SIN_ESPACIADO_PREDETERMINADO"
    SIN_METODO_MATERIALES = "SIN_METODO_MATERIALES"
    SIN_MESES_VALIDOS = "SIN_MESES_VALIDOS"
    RECETA_INCOMPLETA = "RECETA_INCOMPLETA"
    IMPORTE_MATERIALES_FALTANTE = "IMPORTE_MATERIALES_FALTANTE"
    MATERIALES_EN_CERO = "MATERIALES_EN_CERO"
    AJUSTE_FUERA_RANGO = "AJUSTE_FUERA_RANGO"


@dataclass(frozen=True, slots=True)
class Bloqueo:
    codigo: CodigoBloqueo
    paso: int
    mensaje: str
    campo: str | None = None
